"""Centralized Ollama API provider configuration.

This is the single source of truth for the Ollama provider settings used by
both the Flask web app (app.py) and the CLI client (chatbot.py). Values are
read from environment variables with sensible defaults for local Ollama.
"""
import os

# Base URL of the Ollama server (custom endpoint path can be appended later).
OLLAMA_BASE_URL = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")

# Relative API path on the Ollama server used for chat completions.
OLLAMA_CHAT_PATH = os.environ.get("OLLAMA_CHAT_PATH", "/api/chat")

# Full URL to send chat completion requests to.
OLLAMA_URL = f"{OLLAMA_BASE_URL.rstrip('/')}{OLLAMA_CHAT_PATH}"

# Model served by Ollama (e.g. qwen3, llama3.2, mistral, phi3).
OLLAMA_MODEL = os.environ.get("OLLAMA_MODEL", "qwen3")

# Request timeouts (seconds) - generous because local LLMs can be slow.
OLLAMA_TIMEOUT = int(os.environ.get("OLLAMA_TIMEOUT", "300"))

# Stream tokens as they are generated by default.
OLLAMA_STREAM = os.environ.get("OLLAMA_STREAM", "1").lower() not in ("0", "false", "no")